apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.3.1
          ports:
          - containerPort: 5050
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          env:
          - name: PORT
            value: "5050"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice.hipstershop-product-catalog:3550"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice.hipstershop-shipping:50051"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice.hipstershop-payment:50051"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice.hipstershop-email:5000"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice.hipstershop-currency:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice.hipstershop-cart:7070"
          # - name: DISABLE_STATS
          #   value: "1"
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
