apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    env: production
spec:
  selector:
    matchLabels:
      app: frontend
      env: production
  template:
    metadata:
      labels:
        app: frontend
        env: production
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/frontend:v0.3.1
          ports:
          - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
              - name: "Cookie"
                value: "shop_session-id=x-liveness-probe"
          env:
          - name: PORT
            value: "8080"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice.int-sm-gns-hipstershop.cloud.7357.link:3550"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice.int-sm-gns-hipstershop.cloud.7357.link:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice.int-sm-gns-hipstershop.cloud.7357.link:7070"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "recommendationservice.int-sm-gns-hipstershop.cloud.7357.link:8080"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice.int-sm-gns-hipstershop.cloud.7357.link:50051"
          - name: CHECKOUT_SERVICE_ADDR
            value: "checkoutservice.int-sm-gns-hipstershop.cloud.7357.link:5050"
          - name: AD_SERVICE_ADDR
            value: "adservice.int-sm-gns-hipstershop.cloud.7357.link:9555"
          # # ENV_PLATFORM: One of: local, gcp, aws, azure, onprem, alibaba
          # # When not set, defaults to "local" unless running in GKE, otherwies auto-sets to gcp
          # - name: ENV_PLATFORM
          #   value: "aws"
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          # - name: CYMBAL_BRANDING
          #   value: "true"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
