apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hipstershop
# namePrefix: prod-
resources:
- deployment_frontend.yaml
- service_frontend.yaml
- deployment_canary_frontend.yaml
- service_canary_frontend.yaml
