apiVersion: v1
kind: Service
metadata:
  name: frontend-canary
spec:
  type: ClusterIP
  selector:
    app: frontend
    env: canary
  ports:
  - name: http
    port: 80
    targetPort: 8080
    appProtocol: https
